name: talk_ai
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^5.7.0
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  http: ^1.1.2
  injectable: ^2.1.1
  path_provider: ^2.0.14
  provider: ^6.0.5
  rive: ^0.12.4
  share_plus: ^7.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5

dependency_overrides:
  http: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/rive/chat.riv
